# Generated by CMake 3.5.2

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget itkdouble-conversion itksys itkvcl itknetlib itkv3p_netlib itkvnl itkvnl_algo ITKVNLInstantiation ITKCommon itkNetlibSlatec ITKStatistics ITKTransform ITKLabelMap ITKMesh ITKMetaIO ITKSpatialObjects ITKPath ITKQuadEdgeMesh ITKIOImageBase ITKOptimizers ITKPolynomials ITKBiasCorrection ITKKLMRegionGrowing ITKOptimizersv4 ITKWatersheds)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)

# Create imported target itkdouble-conversion
add_library(itkdouble-conversion SHARED IMPORTED)

# Create imported target itksys
add_library(itksys SHARED IMPORTED)

# Create imported target itkvcl
add_library(itkvcl SHARED IMPORTED)

set_target_properties(itkvcl PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/ITK-4.12"
)

# Create imported target itknetlib
add_library(itknetlib SHARED IMPORTED)

set_target_properties(itknetlib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/ITK-4.12"
)

# Create imported target itkv3p_netlib
add_library(itkv3p_netlib SHARED IMPORTED)

set_target_properties(itkv3p_netlib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/ITK-4.12"
)

# Create imported target itkvnl
add_library(itkvnl SHARED IMPORTED)

set_target_properties(itkvnl PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/ITK-4.12"
)

# Create imported target itkvnl_algo
add_library(itkvnl_algo SHARED IMPORTED)

set_target_properties(itkvnl_algo PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/ITK-4.12"
)

# Create imported target ITKVNLInstantiation
add_library(ITKVNLInstantiation SHARED IMPORTED)

# Create imported target ITKCommon
add_library(ITKCommon SHARED IMPORTED)

# Create imported target itkNetlibSlatec
add_library(itkNetlibSlatec SHARED IMPORTED)

# Create imported target ITKStatistics
add_library(ITKStatistics SHARED IMPORTED)

# Create imported target ITKTransform
add_library(ITKTransform SHARED IMPORTED)

# Create imported target ITKLabelMap
add_library(ITKLabelMap SHARED IMPORTED)

# Create imported target ITKMesh
add_library(ITKMesh SHARED IMPORTED)

# Create imported target ITKMetaIO
add_library(ITKMetaIO SHARED IMPORTED)

# Create imported target ITKSpatialObjects
add_library(ITKSpatialObjects SHARED IMPORTED)

# Create imported target ITKPath
add_library(ITKPath SHARED IMPORTED)

# Create imported target ITKQuadEdgeMesh
add_library(ITKQuadEdgeMesh SHARED IMPORTED)

# Create imported target ITKIOImageBase
add_library(ITKIOImageBase SHARED IMPORTED)

# Create imported target ITKOptimizers
add_library(ITKOptimizers SHARED IMPORTED)

# Create imported target ITKPolynomials
add_library(ITKPolynomials SHARED IMPORTED)

# Create imported target ITKBiasCorrection
add_library(ITKBiasCorrection SHARED IMPORTED)

# Create imported target ITKKLMRegionGrowing
add_library(ITKKLMRegionGrowing SHARED IMPORTED)

# Create imported target ITKOptimizersv4
add_library(ITKOptimizersv4 SHARED IMPORTED)

# Create imported target ITKWatersheds
add_library(ITKWatersheds SHARED IMPORTED)

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/ITKTargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
